language: node_js
node_js:
  - 8
os:
  - linux
addons:
  apt:
    packages:
      - libsecret-1-dev
before_install:
  - yarn global add vsce
install:
  - yarn

script:
  - yarn run clean
  - yarn run vscode:prepublish
  - if [ $TRAVIS_ENABLE_COVERAGE == "true" ]; then
        yarn run cover:enable;
    fi
  - if [ $TRAVIS_ENABLE_COVERAGE == "true" ]; then
        yarn run cover:upload;
    fi